<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require_once(APPPATH.'controllers/Secure_area.php');
include('Frmcterbilang.php');
class FrmcreturGudang extends Secure_area{

    public function __construct(){
        parent::__construct();
        $this->load->model('logistik_farmasi/FrmmreturGudang','',TRUE);
        $this->load->model('user/Muser','',TRUE);
        $this->load->library('session');
    }

    public function index(){
        $data['title'] = 'Daftar Penerimaan Barang';
        $userid = $this->session->userid;
        $group = $this->Muser->getIdGudang($userid);

        $data['logistik_farmasi']=$this->FrmmreturGudang->get_amprah($group->id_gudang);
        $this->load->view('logistik_farmasi/Frmvdaftardistribusigudang', $data);
    }

    function retur($id){
        $data['title'] = 'Daftar Penerimaan Barang';
        $userid = $this->session->userid;
        $group = $this->Muser->getIdGudang($userid);
        $data['retur_barang'] = $this->FrmmreturGudang->get_amprah_detail_list($id, $group->id_gudang);
        $data['id_amprah'] = $id;
        $this->load->view('logistik_farmasi/Frmvdaftardetailreturgudang',$data);
    }

    public function edit_data_retur(){
        $batch_no=$this->input->post('batch_no');
        $userid = $this->session->userid;
        $group = $this->Muser->getIdGudang($userid);
        $id_gudang = $group->id_gudang;
        $datajson=$this->FrmmreturGudang->get_data_retur_by_batch($batch_no, $id_gudang)->result();
        echo json_encode($datajson);
    }

    function save_retur_gudang(){
        $userid = $this->session->userid;
        $group = $this->Muser->getIdGudang($userid);
        $id_gudang = $group->id_gudang;

        $id_amprah = $this->input->post('id_amprah');
        $this->FrmmreturGudang->insert_quantity($this->input->post());
        $this->FrmmreturGudang->edit_stok($this->input->post(), $id_gudang);
        redirect('logistik_farmasi/FrmcreturGudang/retur/'.$id_amprah);
    }

    function laporan_retur(){
        $data['title'] = 'Laporan Retur Gudang';

        $data['date_title']='<b>'.date("d F Y").'</b>';
        $data['tgl']=date("Y-m-d");

        $data['message_nodata']="<div class=\"content-header\">
			<div class=\"alert alert-danger alert-dismissable\">
				<button class=\"close\" aria-hidden=\"true\" data-dismiss=\"alert\" type=\"button\">×</button>				
			<h4><i class=\"icon fa fa-close\"></i>
				Silahkan Pilih Tanggal dan Download untuk Melihat Laporan Retur.
			</h4>							
			</div>
		</div>";

        $this->load->view('logistik_farmasi/Frmvlaporanreturgudang',$data);
    }

    function download_laporan_retur($param1='', $param2=''){
        ////EXCEL
        $this->load->library('Excel');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("RS AL Marinir Cilandak")
            ->setLastModifiedBy("RS AL Marinir Cilandak")
            ->setTitle("Laporan Keuangan RS AL Marinir Cilandak")
            ->setSubject("Laporan Keuangan RS AL Marinir Cilandak Document")
            ->setDescription("Laporan Keuangan RS AL Marinir Cilandak, generated by HMIS.")
            ->setKeywords("RS AL Marinir Cilandak")
            ->setCategory("Laporan Keuangan");

        //$objReader = PHPExcel_IOFactory::createReader('Excel2007');
        //$objPHPExcel = $objReader->load("project.xlsx");

        $objReader= PHPExcel_IOFactory::createReader('Excel2007');
        $objReader->setReadDataOnly(true);

        $data_keuangan=$this->FrmmreturGudang->get_report_retur($param1, $param2)->result();

        $objPHPExcel=$objReader->load(APPPATH.'third_party/lap_retur_gudang.xlsx');
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);
        // Add some data
        $objPHPExcel->getActiveSheet()->SetCellValue('A1', "Laporan Retur Gudang");
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:J1');
        $objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

        $objPHPExcel->getActiveSheet()->SetCellValue('A2', "Periode ".date('d F Y', strtotime($param1))." - ".date('d F Y', strtotime($param2)));
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A2:J2');
        $objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('B4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('B4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('C4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('C4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('D4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('D4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('E4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('E4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('F4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('F4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('G4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('G4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('H4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('H4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('I4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('I4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
        $objPHPExcel->getActiveSheet()->getStyle('J4')->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('J4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
        $objPHPExcel->getActiveSheet()->setAutoFilter('A4:J4');

        $rowCount = 5;
        $i=1;
        $tqty = 0;
        $temp_gudang = "";
        foreach($data_keuangan as $row){

            $tqty += $row->qty_retur;

            $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $i);

            if($temp_gudang != $row->gudang_penerima){
                $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->id_amprah);
                $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->tgl_amprah);
                $objPHPExcel->getActiveSheet()->getStyle('C'.$rowCount)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
                $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->gudang_pengirim);
                $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $row->gudang_penerima);
                $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->nm_obat);
                $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->batch_no);
                $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->expire_date);
                $objPHPExcel->getActiveSheet()->getStyle('H'.$rowCount)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
                $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $row->satuank);
                $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $row->qty_retur);

                $temp_gudang = $row->gudang_penerima;
            }else{
                $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->nm_obat);
                $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->batch_no);
                $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->expire_date);
                $objPHPExcel->getActiveSheet()->getStyle('H'.$rowCount)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
                $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $row->satuank);
                $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $row->qty_retur);
            }

            $i++;
            $rowCount++;
        }

        $filename = "Laporan Retur Gudang ".date('d F Y', strtotime($param1))." - ".date('d F Y', strtotime($param2));
        $objPHPExcel->getActiveSheet()->getStyle('H'.$rowCount)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('H'.$rowCount)->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, "Total : ");

        $objPHPExcel->getActiveSheet()->getStyle('J'.$rowCount)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle('J'.$rowCount)->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $tqty);
        header('Content-Disposition: attachment;filename="'.$filename.'.xls"');

        // Rename worksheet (worksheet, not filename)
        $objPHPExcel->getActiveSheet()->setTitle('RS AL Marinir Cilandak');

        // Redirect output to a client’s web browser (Excel2007)
        //clean the output buffer
        ob_end_clean();

        //this is the header given from PHPExcel examples.
        //but the output seems somewhat corrupted in some cases.
        //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        //so, we use this header instead.
        header('Content-type: application/vnd.ms-excel');
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        // $objWriter->save('php://output');
        $this->SaveViaTempFile($objWriter);
    }

    static function SaveViaTempFile($objWriter){
        $filePath = sys_get_temp_dir() . "/" . rand(0, getrandmax()) . rand(0, getrandmax()) . ".tmp";
        $objWriter->save($filePath);
        readfile($filePath);
        unlink($filePath);
    }
}